# Generated by Django 6.0.1 on 2026-01-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Authentication', '0004_commonprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonprofile',
            name='email_for_communication',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='Address',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
