# Generated by Django 6.0.1 on 2026-01-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Authentication', '0005_commonprofile_email_for_communication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonprofile',
            name='whatsApp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
