# Generated by Django 6.0.1 on 2026-01-28 08:09

import App_Authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Authentication', '0006_alter_commonprofile_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_picture/default_profile_picture.png', null=True, upload_to=App_Authentication.utils.rename_profile_picture),
        ),
    ]
