from django.core.management.base import BaseCommand
from App_Admin_Content_Management.models import Languages

class Command(BaseCommand):
    help = 'Seeds the database with a comprehensive list of languages'

    def handle(self, *args, **options):
        # List of languages to seed
        languages_data = [
            {"name": "Afrikaans", "native": "Afrikaans"},
            {"name": "Albanian", "native": "Shqip"},
            {"name": "Amharic", "native": "አማርኛ"},
            {"name": "Arabic", "native": "العربية"},
            {"name": "Armenian", "native": "Հայերեն"},
            {"name": "Azerbaijani", "native": "Azərbaycan"},
            {"name": "Basque", "native": "Euskara"},
            {"name": "Belarusian", "native": "Беларуская"},
            {"name": "Bengali", "native": "বাংলা"},
            {"name": "Bosnian", "native": "Bosanski"},
            {"name": "Bulgarian", "native": "Български"},
            {"name": "Catalan", "native": "Català"},
            {"name": "Cebuano", "native": "Cebuano"},
            {"name": "Chinese (Simplified)", "native": "简体中文"},
            {"name": "Chinese (Traditional)", "native": "繁體中文"},
            {"name": "Corsican", "native": "Corsu"},
            {"name": "Croatian", "native": "Hrvatski"},
            {"name": "Czech", "native": "Čeština"},
            {"name": "Danish", "native": "Dansk"},
            {"name": "Dutch", "native": "Nederlands"},
            {"name": "English", "native": "English"},
            {"name": "Esperanto", "native": "Esperanto"},
            {"name": "Estonian", "native": "Eesti"},
            {"name": "Finnish", "native": "Suomi"},
            {"name": "French", "native": "Français"},
            {"name": "Frisian", "native": "Frysk"},
            {"name": "Galician", "native": "Galego"},
            {"name": "Georgian", "native": "ქართული"},
            {"name": "German", "native": "Deutsch"},
            {"name": "Greek", "native": "Ελληνικά"},
            {"name": "Gujarati", "native": "ગુજરાતી"},
            {"name": "Haitian Creole", "native": "Kreyòl Ayisyen"},
            {"name": "Hausa", "native": "Hausa"},
            {"name": "Hawaiian", "native": "Ōlelo Hawaiʻi"},
            {"name": "Hebrew", "native": "עברית"},
            {"name": "Hindi", "native": "हिन्दी"},
            {"name": "Hmong", "native": "Hmoob"},
            {"name": "Hungarian", "native": "Magyar"},
            {"name": "Icelandic", "native": "Íslenska"},
            {"name": "Igbo", "native": "Igbo"},
            {"name": "Indonesian", "native": "Bahasa Indonesia"},
            {"name": "Irish", "native": "Gaeilge"},
            {"name": "Italian", "native": "Italiano"},
            {"name": "Japanese", "native": "日本語"},
            {"name": "Javanese", "native": "Basa Jawa"},
            {"name": "Kannada", "native": "ಕನ್ನಡ"},
            {"name": "Kazakh", "native": "Қазақ тілі"},
            {"name": "Khmer", "native": "ខ្មែរ"},
            {"name": "Korean", "native": "한국어"},
            {"name": "Kurdish (Kurmanji)", "native": "Kurdî"},
            {"name": "Kyrgyz", "native": "Кыргызча"},
            {"name": "Lao", "native": "ລາວ"},
            {"name": "Latin", "native": "Latina"},
            {"name": "Latvian", "native": "Latviešu"},
            {"name": "Lithuanian", "native": "Lietuvių"},
            {"name": "Luxembourgish", "native": "Lëtzebuergesch"},
            {"name": "Macedonian", "native": "Македонски"},
            {"name": "Malagasy", "native": "Malagasy"},
            {"name": "Malay", "native": "Bahasa Melayu"},
            {"name": "Malayalam", "native": "മലയാളം"},
            {"name": "Maltese", "native": "Malti"},
            {"name": "Maori", "native": "Māori"},
            {"name": "Marathi", "native": "मराठी"},
            {"name": "Mongolian", "native": "Монгол"},
            {"name": "Myanmar (Burmese)", "native": "မြန်မာစာ"},
            {"name": "Nepali", "native": "नेपाली"},
            {"name": "Norwegian", "native": "Norsk"},
            {"name": "Nyanja (Chichewa)", "native": "ChiCheŵa"},
            {"name": "Pashto", "native": "پښتو"},
            {"name": "Persian", "native": "فارسی"},
            {"name": "Polish", "native": "Polski"},
            {"name": "Portuguese", "native": "Português"},
            {"name": "Punjabi", "native": "ਪੰਜਾਬੀ"},
            {"name": "Romanian", "native": "Română"},
            {"name": "Russian", "native": "Русский"},
            {"name": "Samoan", "native": "Gagana Samoa"},
            {"name": "Scots Gaelic", "native": "Gàidhlig"},
            {"name": "Serbian", "native": "Српски"},
            {"name": "Sesotho", "native": "Sesotho"},
            {"name": "Shona", "native": "ChiShona"},
            {"name": "Sindhi", "native": "سنڌي"},
            {"name": "Sinhala (Sinhalese)", "native": "සිංහල"},
            {"name": "Slovak", "native": "Slovenčina"},
            {"name": "Slovenian", "native": "Slovenščina"},
            {"name": "Somali", "native": "Soomaali"},
            {"name": "Spanish", "native": "Español"},
            {"name": "Sundanese", "native": "Basa Sunda"},
            {"name": "Swahili", "native": "Kiswahili"},
            {"name": "Swedish", "native": "Svenska"},
            {"name": "Tagalog (Filipino)", "native": "Filipino"},
            {"name": "Tajik", "native": "Тоҷикӣ"},
            {"name": "Tamil", "native": "தமிழ்"},
            {"name": "Telugu", "native": "తెలుగు"},
            {"name": "Thai", "native": "ไทย"},
            {"name": "Turkish", "native": "Türkçe"},
            {"name": "Ukrainian", "native": "Українська"},
            {"name": "Urdu", "native": "اردو"},
            {"name": "Uzbek", "native": "Oʻzbek"},
            {"name": "Vietnamese", "native": "Tiếng Việt"},
            {"name": "Welsh", "native": "Cymraeg"},
            {"name": "Xhosa", "native": "isiXhosa"},
            {"name": "Yiddish", "native": "ייִדיש"},
            {"name": "Yoruba", "native": "Yorùbá"},
            {"name": "Zulu", "native": "isiZulu"},
        ]

        count = 0
        for data in languages_data:
            obj, created = Languages.objects.get_or_create(
                language_name=data['name'],
                defaults={'language_name_in_native': data['native']}
            )
            if created:
                count += 1
                self.stdout.write(self.style.SUCCESS(f'Created: {data["name"]}'))
            else:
                self.stdout.write(f'Already exists: {data["name"]}')

        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {count} new languages.'))
