# Generated by Django 6.0.1 on 2026-01-26 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('short_bio', models.CharField(max_length=300)),
                ('full_bio', models.TextField(blank=True, null=True)),
                ('expertise', models.JSONField(default=list)),
                ('teaching_languages', models.JSONField(default=list)),
                ('organization', models.CharField(blank=True, max_length=150, null=True)),
                ('years_of_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_courses', models.PositiveIntegerField(default=0)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('verified_badge', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
