# Generated by Django 6.0.1 on 2026-01-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Instructors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='expertise',
        ),
    ]
