# Generated by Django 6.0.1 on 2026-01-27 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Instructors', '0002_remove_instructorprofile_expertise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructorprofile',
            old_name='title',
            new_name='designation',
        ),
    ]
