# Generated by Django 6.0.1 on 2026-01-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Instructors', '0003_rename_title_instructorprofile_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='designation',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='organization',
            field=models.CharField(default='qq', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='years_of_experience',
            field=models.FloatField(default=0),
        ),
    ]
