# Generated by Django 6.0.1 on 2026-01-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Instructors', '0004_alter_instructorprofile_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
