# Generated by Django 6.0.1 on 2026-01-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Instructors', '0005_alter_instructorprofile_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='short_bio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
