# Generated by Django 6.0.1 on 2026-01-22 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=100)),
                ('language_name_in_native', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
    ]
