# Generated by Django 6.0.1 on 2026-01-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin_Content_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='language_name_in_native',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
