# Generated by Django 6.0.1 on 2026-01-25 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin_Content_Management', '0002_alter_languages_language_name_in_native'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timezones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timezone_name', models.CharField(max_length=100)),
                ('gmt_offset', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Timezones',
            },
        ),
    ]
