# Generated by Django 6.0.1 on 2026-01-27 10:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin_Content_Management', '0003_timezones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Subject Tags',
            },
        ),
    ]
