# Generated by Django 6.0.1 on 2026-01-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin_Content_Management', '0004_subject_tag'),
        ('App_Learners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnerprofile',
            name='interests',
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='App_Admin_Content_Management.subject_tag'),
        ),
    ]
